apiVersion: agentchaos.dev/v1alpha1
kind: Workflow
metadata:
  name: continue-after-fail
spec:
  failFast: false
  tasks:
    - serial:
        - ../probe/process-kill.yaml
        - ../probe/file-lock.yaml
